version: "3.8"
services:
  accessibility_api_database:
    image: mongo:4.4.3
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
  accessibility_api_service:
#    platform: linux/amd64
    build: .
    restart: always
    ports:
      - 3000:3000
    links:
      - accessibility_api_database
